"""Conversion between ProtocolCandidate (schema, free-text FieldValues) and the typed params dict
the optimizer needs, given an explicit ParameterSpace (see cli/project.py for why the space is
never inferred).
"""

from __future__ import annotations

from materials_synthesis_agent.optimize.space import ParameterSpace, ParamValue
from materials_synthesis_agent.schema import FieldValue, ProtocolCandidate


def protocol_to_params(candidate: ProtocolCandidate, space: ParameterSpace) -> dict[str, ParamValue]:
    """Pull the values a ParameterSpace's specs need off a ProtocolCandidate's named fields
    (temperature_c, time_hours, solvent, etc. -- the fixed fields on the schema) and coerce them
    to the right type. Raises clearly if a required field is missing or unparsable, rather than
    silently dropping it -- an incomplete params dict would corrupt the GP's training data."""
    params: dict[str, ParamValue] = {}
    for spec in space.specs:
        field: FieldValue | None = getattr(candidate, spec.name, None)
        if field is None:
            raise ValueError(
                f"Protocol candidate {candidate.id} has no value for '{spec.name}', "
                f"which parameter_space.json requires. Can't build an Observation from it."
            )
        if spec.kind == "continuous":
            try:
                params[spec.name] = float(field.value)
            except ValueError as exc:
                raise ValueError(f"'{spec.name}' value {field.value!r} on candidate {candidate.id} isn't numeric.") from exc
        else:
            params[spec.name] = field.value
    return params


def params_to_new_candidate(params: dict[str, ParamValue], target_id: str) -> ProtocolCandidate:
    """Build a ProtocolCandidate from a BO suggestion's params dict. Every field is flagged
    inferred=True -- it wasn't read from any source, it was generated by the optimizer, which is
    exactly what `inferred` is for on a FieldValue with no citation."""
    from materials_synthesis_agent.schema import ProtocolSource

    kwargs = {}
    for name, value in params.items():
        if name in {"temperature_c", "time_hours", "concentration_molar", "solvent", "modulator"}:
            kwargs[name] = FieldValue(value=str(value), inferred=True)
    return ProtocolCandidate(target_id=target_id, source=ProtocolSource.BO_SUGGESTED, **kwargs)
