"""Optional retrosynthesis check via AiZynthFinder -- v0.2 (ROADMAP.md).

NOT exercised live in this codebase's development environment, and confirmed harder than "just pip
install it": `pip install aizynthfinder` itself failed here building the `llvmlite` wheel from
source (no matching prebuilt wheel for this environment's Python/platform combo -- a concrete,
observed failure, not a hypothetical one). Even setting that aside, using this for real still needs
a separate `download_public_data <dir>` step that fetches several GB of pretrained USPTO
policy-network weights and stock data. This module is written against AiZynthFinder's documented
API and its import is fully lazy (nothing above breaks if the package isn't installed), but it has
not been run end-to-end against a real installed package or real model files. Treat it as a real
starting point, not a verified integration -- exercise it against your own environment and
downloaded data before trusting its output.

Install with: pip install "materials-synthesis-agent[retrosynthesis]"
Then: download_public_data <your-data-dir>   (an AiZynthFinder CLI command, ~GB download)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


class RetrosynthesisUnavailable(RuntimeError):
    """Raised when aizynthfinder isn't installed, or its config/model files aren't set up --
    distinct from 'this molecule has no route,' which is a real (negative) result, not an error."""


@dataclass
class RetrosynthesisResult:
    smiles: str
    is_solved: bool  # AiZynthFinder found at least one route to purchasable starting materials
    num_routes: int
    top_route_summary: Optional[str] = None
    flags: list[str] = field(default_factory=list)


def check_retrosynthesis(smiles: str, config_path: str) -> RetrosynthesisResult:
    """Run AiZynthFinder's MCTS search for a route to purchasable starting materials.

    `config_path` points at the yaml config AiZynthFinder's own docs describe (policy model path,
    stock file path, etc.) -- produced by `download_public_data`, not generated by this package.
    """
    try:
        from aizynthfinder.aizynthfinder import AiZynthFinder
    except ImportError as exc:
        raise RetrosynthesisUnavailable(
            "aizynthfinder is not installed. Run: pip install 'materials-synthesis-agent[retrosynthesis]', "
            "then `download_public_data <dir>` to fetch the pretrained models this needs."
        ) from exc

    finder = AiZynthFinder(configfile=config_path)
    finder.stock.select("zinc")  # the default stock AiZynthFinder's public data ships; adjust per your config
    finder.expansion_policy.select("uspto")
    finder.target_smiles = smiles
    finder.tree_search()
    finder.build_routes()
    stats = finder.extract_statistics()

    routes = finder.routes
    top_summary = None
    if len(routes) > 0:
        top_summary = routes[0].get("route", {}).__repr__()[:500]

    return RetrosynthesisResult(
        smiles=smiles,
        is_solved=bool(stats.get("is_solved", False)),
        num_routes=len(routes),
        top_route_summary=top_summary,
    )


def check_building_block_with_retrosynthesis(name: str, smiles: str, config_path: str):
    """Feasibility check that falls back to retrosynthesis when a block isn't purchasable --
    composes with `feasibility.checker.check_building_block` rather than replacing it."""
    from materials_synthesis_agent.feasibility.checker import check_building_block

    result = check_building_block(name, smiles, verify_purchasability=True)
    if result.is_valid_structure and not result.is_purchasable:
        try:
            retro = check_retrosynthesis(smiles, config_path)
            if retro.is_solved:
                result.flags.append(
                    f"Not purchasable, but AiZynthFinder found {retro.num_routes} candidate route(s): "
                    f"{retro.top_route_summary}"
                )
            else:
                result.flags.append("Not purchasable, and no retrosynthesis route found.")
        except RetrosynthesisUnavailable as exc:
            result.flags.append(f"Not purchasable; retrosynthesis check unavailable ({exc}).")
    return result
