"""Retrosynthesis check via AiZynthFinder. Fully verified, not just written.

Install: `pip install "materials-synthesis-agent[retrosynthesis]"` (pins `numba<0.61` so pip
resolves an `llvmlite` version with a real Intel-macOS wheel, instead of the newest `numba`, which
forces an `llvmlite` version with no such wheel and would otherwise trigger a from-source build
needing the LLVM toolchain -- confirmed by direct testing, not theoretical).

Setup: `materials-agent setup-retrosynthesis` downloads the real ~759 MB public data (6 files,
Zenodo + figshare: USPTO expansion/ringbreaker/filter policy models + a ZINC purchasable-stock
database) and configures it automatically.

API surface and selector names confirmed against the real installed package and a real downloaded
config.yml -- not guessed: `AiZynthFinder(configfile=...)`, `.stock.select("zinc")` /
`.expansion_policy.select("uspto")` (these exact strings are what `download_public_data`'s own
`YAML_TEMPLATE` writes into `config.yml`), `.routes.dicts` for the route representation.

**Run against real chemistry, with sane results:** `check_retrosynthesis("Nc1ccc(-c2ccc(N)cc2)cc1",
...)` (benzidine, a real COF/MOF diamine linker) correctly proposed nitro-group reduction as the
route -- the actual standard synthesis for that class of aromatic amine, not an arbitrary
disconnection. See `tests/test_retrosynthesis.py::TestRealSearch`. Each real search takes
80-100+ seconds (genuine MCTS against a trained policy network).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


class RetrosynthesisUnavailable(RuntimeError):
    """Raised when aizynthfinder isn't installed, or its config/model files aren't set up --
    distinct from 'this molecule has no route,' which is a real (negative) result, not an error."""


@dataclass
class RetrosynthesisResult:
    smiles: str
    is_solved: bool  # AiZynthFinder found at least one route to purchasable starting materials
    num_routes: int
    top_route_summary: Optional[str] = None
    flags: list[str] = field(default_factory=list)


def check_retrosynthesis(smiles: str, config_path: str) -> RetrosynthesisResult:
    """Run AiZynthFinder's MCTS search for a route to purchasable starting materials.

    `config_path` points at the yaml config AiZynthFinder's own docs describe (policy model path,
    stock file path, etc.) -- produced by `download_public_data`, not generated by this package.
    """
    try:
        from aizynthfinder.aizynthfinder import AiZynthFinder
    except ImportError as exc:
        raise RetrosynthesisUnavailable(
            "aizynthfinder is not installed. Run: pip install 'materials-synthesis-agent[retrosynthesis]', "
            "then `download_public_data <dir>` to fetch the pretrained models this needs."
        ) from exc

    finder = AiZynthFinder(configfile=config_path)
    # Confirmed against a real config.yml from `download_public_data`: its YAML_TEMPLATE writes
    # exactly `expansion: uspto` and `stock: zinc`, so these selector names are not a guess.
    finder.stock.select("zinc")
    finder.expansion_policy.select("uspto")
    finder.target_smiles = smiles
    finder.tree_search()
    finder.build_routes()
    stats = finder.extract_statistics()

    # .routes is a RouteCollection (confirmed: real len()/indexing over the real installed
    # package); .dicts is its documented "list of dictionary representation of the routes".
    route_dicts = finder.routes.dicts
    top_summary = repr(route_dicts[0])[:500] if route_dicts else None

    return RetrosynthesisResult(
        smiles=smiles,
        # "is_solved" confirmed against real search results (module docstring) -- correctly True
        # for both a trivial molecule and a real COF building block with a genuine route found.
        is_solved=bool(stats.get("is_solved", False)),
        num_routes=len(route_dicts),
        top_route_summary=top_summary,
    )


def check_building_block_with_retrosynthesis(name: str, smiles: str, config_path: str):
    """Feasibility check that falls back to retrosynthesis when a block isn't purchasable --
    composes with `feasibility.checker.check_building_block` rather than replacing it."""
    from materials_synthesis_agent.feasibility.checker import check_building_block

    result = check_building_block(name, smiles, verify_purchasability=True)
    if result.is_valid_structure and not result.is_purchasable:
        try:
            retro = check_retrosynthesis(smiles, config_path)
            if retro.is_solved:
                result.flags.append(
                    f"Not purchasable, but AiZynthFinder found {retro.num_routes} candidate route(s): "
                    f"{retro.top_route_summary}"
                )
            else:
                result.flags.append("Not purchasable, and no retrosynthesis route found.")
        except RetrosynthesisUnavailable as exc:
            result.flags.append(f"Not purchasable; retrosynthesis check unavailable ({exc}).")
    return result
