"""Optional retrosynthesis check via AiZynthFinder -- v0.2 (ROADMAP.md).

Install status: `aizynthfinder` now installs cleanly in this project's dev environment (see the
`retrosynthesis` extra in pyproject.toml -- the fix was pinning `numba<0.61` so pip resolves an
`llvmlite` version with a real Intel-macOS wheel, instead of the newest `numba`, which forces an
`llvmlite` version with no such wheel and triggers a from-source build needing the LLVM toolchain).

API surface confirmed against the real installed package (not guessed): `AiZynthFinder(configfile=
...)`, `.stock`/`.expansion_policy` are instance attributes with `.select(value, append=False)`,
`.routes` is a `RouteCollection` with real `len()`/indexing, and `.routes.dicts` gives the
documented list-of-dict route representation used below.

**Still NOT exercised against a real search**, because that needs `download_public_data <dir>` --
a separate multi-GB fetch of pretrained USPTO policy weights and stock data, not yet done. That
means: the exact stock/policy *names* to pass to `.select()` (guessed below as `"zinc"`/`"uspto"`,
AiZynthFinder's typical public-data naming) and the exact key `extract_statistics()` uses for
"solved" status are unverified against a real config.yml. Confirm both against your own downloaded
data's config before trusting output beyond "did it run without crashing."

Install with: pip install "materials-synthesis-agent[retrosynthesis]"
Then: download_public_data <your-data-dir>   (an AiZynthFinder CLI command, ~GB download)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


class RetrosynthesisUnavailable(RuntimeError):
    """Raised when aizynthfinder isn't installed, or its config/model files aren't set up --
    distinct from 'this molecule has no route,' which is a real (negative) result, not an error."""


@dataclass
class RetrosynthesisResult:
    smiles: str
    is_solved: bool  # AiZynthFinder found at least one route to purchasable starting materials
    num_routes: int
    top_route_summary: Optional[str] = None
    flags: list[str] = field(default_factory=list)


def check_retrosynthesis(smiles: str, config_path: str) -> RetrosynthesisResult:
    """Run AiZynthFinder's MCTS search for a route to purchasable starting materials.

    `config_path` points at the yaml config AiZynthFinder's own docs describe (policy model path,
    stock file path, etc.) -- produced by `download_public_data`, not generated by this package.
    """
    try:
        from aizynthfinder.aizynthfinder import AiZynthFinder
    except ImportError as exc:
        raise RetrosynthesisUnavailable(
            "aizynthfinder is not installed. Run: pip install 'materials-synthesis-agent[retrosynthesis]', "
            "then `download_public_data <dir>` to fetch the pretrained models this needs."
        ) from exc

    finder = AiZynthFinder(configfile=config_path)
    # Selector names below are AiZynthFinder's typical public-data naming, NOT verified against a
    # real downloaded config (see module docstring) -- check these against your own config.yml.
    finder.stock.select("zinc")
    finder.expansion_policy.select("uspto")
    finder.target_smiles = smiles
    finder.tree_search()
    finder.build_routes()
    stats = finder.extract_statistics()

    # .routes is a RouteCollection (confirmed: real len()/indexing over the real installed
    # package); .dicts is its documented "list of dictionary representation of the routes".
    route_dicts = finder.routes.dicts
    top_summary = repr(route_dicts[0])[:500] if route_dicts else None

    return RetrosynthesisResult(
        smiles=smiles,
        # "is_solved" is AiZynthFinder's documented statistics key as of the version installed
        # here; still unverified against a real search result (see module docstring).
        is_solved=bool(stats.get("is_solved", False)),
        num_routes=len(route_dicts),
        top_route_summary=top_summary,
    )


def check_building_block_with_retrosynthesis(name: str, smiles: str, config_path: str):
    """Feasibility check that falls back to retrosynthesis when a block isn't purchasable --
    composes with `feasibility.checker.check_building_block` rather than replacing it."""
    from materials_synthesis_agent.feasibility.checker import check_building_block

    result = check_building_block(name, smiles, verify_purchasability=True)
    if result.is_valid_structure and not result.is_purchasable:
        try:
            retro = check_retrosynthesis(smiles, config_path)
            if retro.is_solved:
                result.flags.append(
                    f"Not purchasable, but AiZynthFinder found {retro.num_routes} candidate route(s): "
                    f"{retro.top_route_summary}"
                )
            else:
                result.flags.append("Not purchasable, and no retrosynthesis route found.")
        except RetrosynthesisUnavailable as exc:
            result.flags.append(f"Not purchasable; retrosynthesis check unavailable ({exc}).")
    return result
